# Generated by Django 3.2.9 on 2021-12-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211207_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.CharField(default='name', max_length=30),
        ),
    ]
