# Generated by Django 3.2.9 on 2021-12-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_project_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('WEBGL_GAME', 'WebGL Game'), ('REPL', 'repl')], default='R', max_length=20),
        ),
    ]
